Orms.WebApp/Controllers/CalorificValuesController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using Orms.DataAccessFactory;
using Orms.DataAccessFactory.OperationFactories;
using Orms.DataAccessHelper.Operations.Interfaces;
using Orms.Domains.Enums;
using Orms.Domains.Units;
using Orms.Models;

namespace Orms.WebApp.Controllers
{
    public class CalorificValuesController : Controller
    {
        private readonly IGasStorageOperation GasStorageOperation;
        private readonly ICalorificValueOperation Operation;

        public CalorificValuesController()
        {
            var orm = OrmFactory.Get(Application.OrmName);
            Operation = OperationFactory.GetCalorificValueOperation(orm, Application.ConnectionString);
            GasStorageOperation = OperationFactory.GetGasStorageOperation(orm, Application.ConnectionString);
        }

        public ActionResult Index()
        {
            var gasStorages = GasStorageOperation.GetAll();
            return View(gasStorages);
        }

        public ActionResult Details(int id, DateTime? gasDay = null)
        {
            if (gasDay == null)
            {
                gasDay = DateTime.Now;
            }

            var gasStorage = GasStorageOperation.Get(id);

            if (gasStorage == null)
            {
                return HttpNotFound();
            }

            var gd = new GasDay((DateTime)gasDay);

            var cv = Operation.GetForGasDay(gasStorage, gd.First);

            if (cv != null) return View(cv);

            cv = new CalorificValue()
            {
                GasStorage = gasStorage,
                GasDay = gd.First,
            };

            var values = new List<EnergyCalorificValue>();

            for (var index = 0; index < new GasDay(DateTime.Today).Hours.Count(); index++)
            {
                values.Add(new EnergyCalorificValue()
                {
                    CalorificValue = cv,
                    HourIndex = index,
                    Energy = new UnitValue(0, Unit.Kwh)
                });
            }

            cv.Values = values;

            return View(cv);
        }

        public ActionResult Create(FormCollection collection)
        {
            var values = collection
                .GetValues("value.Energy.Value")
                .Select(v => Decimal.Parse(v));

            var cvValues = new List<EnergyCalorificValue>();

            var gasDay = collection.GetValue("gasDay") == null
                ? GasDay.Today.First
                : TryParseDaeTime(collection.Get("gasDay"));

            var gasStorage = GasStorageOperation.Get(Int32.Parse(collection["gasStorageId"]));

            var cv = new CalorificValue()
            {
                GasStorage = gasStorage,
                GasDay = gasDay
            };

            for (var index = 0; index < values.Count(); index++)
            {
                var val = new EnergyCalorificValue()
                {
                    HourIndex = index,
                    Energy = new UnitValue(values.ElementAt(index), Unit.Kwh),
                    CalorificValue = cv
                };

                cvValues.Add(val);
            }

            cv.Values = cvValues;

            Operation.Add(cv, cv.Values);

            return RedirectToAction("Details", new { id = gasStorage.Id, gasDay = gasDay });
        }

        private static DateTime TryParseDaeTime(string value)
        {
            var gasDay = GasDay.Today.First;

            var status = DateTime.TryParse(value, out gasDay);

            if (!status)
            {
                status = DateTime.TryParseExact(value, "yyyyMMdd", null, System.Globalization.DateTimeStyles.None, out gasDay);
            }

            if (status)
            {
                gasDay = new GasDay(gasDay).First;
            }

            return gasDay;
        }
    }
}

Orms.WebApp/Views/CalorificValues/Details.cshtml
@model Orms.Models.CalorificValue

@{
    ViewBag.Title = "Details";
}


<h2>Details</h2>

<div>
    <h4>Calorific value for @Model.GasStorage.Name for @Model.GasDay</h4>
    <hr />
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        <div class="form-group">
            @Html.Label("GasDay", "", htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.Editor("gasDay", new {htmlAttributes = new {@class = "form-control", @Value = Model.GasDay.ToString()}})
                @Html.ValidationMessage("gasDay", "", new {@class = "text-danger"})
            </div>
        </div>

        @Html.Hidden("gasStorageId", @Model.GasStorage.Id.ToString())

        <div class="form-group">
            <input type="submit" value="Change" class="btn btn-default" />
            <input type="reset" value="Reset" class="btn btn-default" />
        </div>
    }

    @using (Html.BeginForm("Create", "CalorificValues", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <table class="table">
            <tr>
                <th>
                    Hour index
                </th>
                <th>
                    Value
                </th>
                <th>
                    Unit
                </th>
            </tr>

            @foreach (var value in @Model.Values)
            {
                <tr>
                    <td>
                        @value.HourIndex
                    </td>
                    <td>
                        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
                        <div class="form-group">
                            @Html.LabelFor(model => value.Energy.Value, "", htmlAttributes: new {@class = "control-label col-md-2"})
                            <div class="col-md-10">
                                @Html.EditorFor(model => value.Energy.Value, new {htmlAttributes = new {@class = "form-control"}})
                                @Html.ValidationMessageFor(model => value.Energy.Value, "", new {@class = "text-danger"})
                            </div>
                        </div>
                    </td>
                    <td>
                        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
                        <div class="form-group">
                            @Html.LabelFor(model => value.Energy.Unit, "", htmlAttributes: new {@class = "control-label col-md-2"})
                            <div class="col-md-10">
                                @Html.DisplayFor(model => value.Energy.Unit, new {htmlAttributes = new {@class = "form-control"}})
                                @Html.ValidationMessageFor(model => value.Energy.Unit, "", new {@class = "text-danger"})
                            </div>
                        </div>
                    </td>
                </tr>
            }

        </table>

        @Html.Hidden("gasStorageId", @Model.GasStorage.Id.ToString())
        @Html.Hidden("gasDay", @Model.GasDay)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
                <input type="reset" value="Reset" class="btn btn-default" />
            </div>
        </div>
    }


</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

Orms.WebApp/Views/CalorificValues/Index.cshtml
@model IEnumerable<Orms.Models.GasStorage>

@{
    ViewBag.Title = "Index";
}

<h2>GasStorage lists</h2>

<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.Id })
            </td>
        </tr>
    }

</table>