Orms.WebApp/Controllers/GasStoragesController.cs
using System;
using System.Web.Mvc;
using Orms.DataAccessFactory;
using Orms.DataAccessFactory.OperationFactories;
using Orms.DataAccessHelper.Operations.Interfaces;
using Orms.Domains.Enums;
using Orms.Models;
using Orms.WebApp.Models;

namespace Orms.WebApp.Controllers
{
    public class GasStoragesController : Controller
    {
        private readonly IGasStorageOperation Operation;
        private readonly IAccessPointOperation AccessPointOperation;

        public GasStoragesController()
        {
            var orm = OrmFactory.Get(Application.OrmName);
            Operation = OperationFactory.GetGasStorageOperation(orm, Application.ConnectionString);
            AccessPointOperation = OperationFactory.GetAccessPointOperation(orm, Application.ConnectionString);
        }

        public ActionResult Index()
        {
            var gasStorages = Operation.GetAll();
            return View(gasStorages);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name")] GasStorage gasStorage)
        {
            if (ModelState.IsValid)
            {
                Operation.Add(gasStorage);
                return RedirectToAction("Index");
            }

            return View(gasStorage);
        }

        public ActionResult Details(int id)
        {
            var gasStorage = Operation.Get(id);

            if (gasStorage == null)
            {
                return HttpNotFound();
            }

            gasStorage.AccessPoints = AccessPointOperation.GetBy(gasStorage);

            var model = new GasStorageDetailsViewModel()
            {
                GasStorage = gasStorage,

            };

            ViewBag.AccessPointId = new SelectList(gasStorage.AccessPoints, "SelectedAccessPointId", "Code");
            return View(model);
        }

        public ActionResult CreateAccessPoint(FormCollection collection)
        {
            var gasStorageId = Int32.Parse(collection["GasStorageId"]);

            if (ModelState.IsValid)
            {
                var gasStorage = Operation.Get(gasStorageId);

                if (gasStorage == null)
                {
                    return HttpNotFound();
                }

                var ap = new AccessPoint()
                {
                    Code = collection["NewAccessPoint.Code"],
                    GasStorage = gasStorage
                };

                AccessPointOperation.Add(ap);
                return RedirectToAction("Details", new { id = gasStorage.Id });
            }

            return RedirectToAction("Details", new { id = gasStorageId });
        }

        public ActionResult CreateAccessPointFlow(FormCollection collection)
        {
            var selectedAccessPointId = Int32.Parse(collection["SelectedAccessPointId"]);

            if (ModelState.IsValid)
            {
                var ap = AccessPointOperation.Get(selectedAccessPointId);

                if (ap == null)
                {
                    return HttpNotFound();
                }

                var apf = new AccessPointFlow()
                {
                    AccessPoint = ap,
                    Direction = collection["NewAccessPointFlow.Direction"] == "0" ?
                        DirectionType.Injection :
                        DirectionType.Withdrawal,
                };

                AccessPointOperation.Add(apf, selectedAccessPointId);

                return RedirectToAction("Details", new { id = ap.GasStorage.Id });
            }
            else
            {
                var ap = AccessPointOperation.Get(selectedAccessPointId);

                if (ap == null)
                {
                    return HttpNotFound();
                }

                return RedirectToAction("Details", new { id = ap.GasStorage.Id });
            }
        }
    }
}

Orms.WebApp/Views/GasStorages/Create.cshtml
@model Orms.Models.GasStorage

@{
    ViewBag.Title = "Create";
}

<h2>Add new GasStorage</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
                <input type="reset" value="Reset" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Orms.WebApp/Views/GasStorages/Details.cshtml
@using Orms.Models.Extensions
@model Orms.WebApp.Models.GasStorageDetailsViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Gas storage @Model.GasStorage.Name</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GasStorage.Name)
        </dd>

    </dl>

    <h4>Add new access point</h4>
    @using (Html.BeginForm("CreateAccessPoint", "GasStorages", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(model => model.NewAccessPoint.Code, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NewAccessPoint.Code, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NewAccessPoint.Code, "", new { @class = "text-danger" })
                </div>
            </div>

            @Html.HiddenFor(model => model.GasStorageId, new { @class = "form-control", @Value = @Model.GasStorage.Id })
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                    <input type="reset" value="Reset" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <h4>Add new access point flow</h4>
    @using (Html.BeginForm("CreateAccessPointFlow", "GasStorages", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(model => model.NewAccessPointFlow.Direction, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EnumDropDownListFor(model => model.NewAccessPointFlow.Direction, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.NewAccessPointFlow.Direction, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SelectedAccessPointId, "AccessPoint", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("SelectedAccessPointId", Model.GasStorage.AccessPoints.Select(ap => new SelectListItem() { Value = ap.Id.ToString(), Text = ap.Code }), htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.SelectedAccessPointId, "", new { @class = "text-danger" })
                </div>
            </div>

            @Html.HiddenFor(model => model.GasStorageId, new { @class = "form-control", @Value = @Model.GasStorage.Id })

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                    <input type="reset" value="Reset" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <h4>AccessPoint lists</h4>
    <table class="table">
        <tr>
            <th>
                Name
            </th>
            <th></th>
        </tr>
        @foreach (var item in Model.GasStorage.AccessPoints)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Code)
                </td>
                <td></td>
            </tr>
            foreach (var apf in item.AccessPointFlows)
            {
                <tr>
                    <td></td>
                    <td>
                        @Html.DisplayFor(modelItem => apf.Direction)
                    </td>
                </tr>
            }
        }
    </table>
</div>

<p>
    @Html.ActionLink("Back to List", "Index")
</p>

Orms.WebApp/Views/GasStorages/Index.cshtml
@model IEnumerable<Orms.Models.GasStorage>

@{
    ViewBag.Title = "Index";
}

<h2>GasStorage lists</h2>

<p>
    @Html.ActionLink("Create new Gas storage", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.Id })
            </td>
        </tr>
    }

</table>