Orms.WebApp/Controllers/NominationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System;
using System.Web;
using System.Web.Mvc;
using Orms.DataAccessFactory;
using Orms.DataAccessFactory.OperationFactories;
using Orms.DataAccessHelper.Operations.Interfaces;
using Orms.Domains.Exceptions;
using Orms.Instractures;
using Orms.Models;
using Orms.WebApp.Models;
using System.Web.Mvc;
using Orms.DataAccessFactory;
using Orms.DataAccessFactory.OperationFactories;
using Orms.DataAccessHelper.Operations.Interfaces;
using Orms.Domains.Enums;
using Orms.Domains.Exceptions;
using Orms.Domains.Units;
using Orms.Models;
using Orms.Models.Extensions;
using Orms.WebApp.Models;

namespace Orms.WebApp.Controllers
{
    public class NominationsController : Controller
    {
        private readonly IGasStorageOperation GasStorageOperation;
        private readonly IAccessPointOperation AccessPointOperation;
        private readonly ICalorificValueOperation CalorificValueOperation;
        private readonly IContractorOperation ContractorOperation;
        private readonly IAgreementOperation AgreementOperation;
        private readonly INominationOperation Operation;

        public NominationsController()
        {
            var orm = OrmFactory.Get(Application.OrmName);
            Operation = OperationFactory.GetNominationOperation(orm, Application.ConnectionString);
            GasStorageOperation = OperationFactory.GetGasStorageOperation(orm, Application.ConnectionString);
            CalorificValueOperation = OperationFactory.GetCalorificValueOperation(orm, Application.ConnectionString);
            ContractorOperation = OperationFactory.GetContractorOperation(orm, Application.ConnectionString);
            AccessPointOperation = OperationFactory.GetAccessPointOperation(orm, Application.ConnectionString);
            AgreementOperation = OperationFactory.GetAgreementOperation(orm, Application.ConnectionString);
        }

        public ActionResult Index(DateTime? gasDay = null)
        {
            IEnumerable<Nomination> nominations;

            if (gasDay == null)
            {
                nominations = Operation.GetBy(GasDay.Today.First);
            }
            else
            {
                var datetime = (DateTime) gasDay;
                nominations = Operation.GetBy(new GasDay(datetime).First);
            }

            return View(new NominationListViewModel() { GasDay = gasDay ?? GasDay.Today.First, Nominations = nominations });
        }

        public ActionResult Create(DateTime? gasDay = null)
        {
            var nomination = new Nomination();

            var values = new List<NominationValue>();

            for (var index = 0; index < new GasDay(DateTime.Today).Hours.Count(); index++)
            {
                values.Add(new NominationValue()
                {
                    HourIndex = index,
                    Energy = new UnitValue(0, Unit.Kwh),
                    Volume = new UnitValue(0, Unit.M3)
                });
            }

            nomination.Values = values;
            nomination.GasDay = GasDay.Today.First;

            var model = new NominationCreateViewModel()
            {
                Nomination = nomination,
                Contractors = ContractorOperation.GetAll().Select(c => new SelectListItem() { Value = c.Id.ToString(), Text = c.Name }),
                GasStorages = GasStorageOperation.GetAll().Select(g => new SelectListItem() { Value = g.Id.ToString(), Text = g.Name }),
            };

            return View(model);
        }

        public ActionResult Get(int gasStorageId, DateTime? gasDay = null)
        {
            var day = gasDay == null ? new GasDay(DateTime.Now).First : new GasDay((DateTime)gasDay).First;

            var gasStorage = GasStorageOperation.Get(gasStorageId);
            gasStorage.AccessPoints = AccessPointOperation.GetBy(gasStorage);
            var cv = CalorificValueOperation.GetForGasDay(gasStorage, day);

            if (cv != null)
            {
                return Json(cv.Values.Select(cvv => new { HourIndex = cvv.HourIndex, Value = cvv.Energy}), JsonRequestBehavior.AllowGet);
            }

            var values = GetEmptyCV();

            return Json(values.Select(cvv => new { HourIndex = cvv.HourIndex, Value = cvv.Energy }), JsonRequestBehavior.AllowGet);
        }

        private static List<EnergyCalorificValue> GetEmptyCV(CalorificValue cv = null)
        {
            var values = new List<EnergyCalorificValue>();

            for (var index = 0; index < new GasDay(DateTime.Today).Hours.Count(); index++)
            {
                values.Add(new EnergyCalorificValue()
                {
                    HourIndex = index,
                    Energy = new UnitValue(0, Unit.Kwh),
                    CalorificValue = cv
                });
            }

            return values;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FormCollection collection)
        {
            var gasDay = DateTime.Parse(collection["Nomination.GasDay"]);
            var gasStorage = GasStorageOperation.Get(Int32.Parse(collection["SelectedGasStorageId"]));
            var contractor = ContractorOperation.Get(Int32.Parse(collection["SelectedContractorId"]));

            var agreements = AgreementOperation.GetAll(contractor, gasStorage);

            if (!agreements.Any(a => a.Start <= gasDay && a.End >= gasDay))
            {
                throw new AgreementExistException();
            }

            var energyValue = collection.GetValues("value.Energy.Value")
                .Select(v => Decimal.Parse(v.Replace('.', ',')));

            var volumeValue = collection.GetValues("value.Volume.Value")
                .Select(v => Decimal.Parse(v.Replace('.', ',')));

            var accespoints = AccessPointOperation.GetBy(gasStorage);
            var commnet = collection["Nomination.Comment"];
            var directionType = EnumHelper.ParseEnum<DirectionType>(collection["DirectionType"]);
            var cv = CalorificValueOperation.GetForGasDay(gasStorage, gasDay);
            var name = collection["Nomination.Name"];

            if (cv == null)
            {
                cv = new CalorificValue()
                {
                    GasStorage = gasStorage,
                    GasDay = gasDay
                };

                var cvValues = GetEmptyCV(cv);

                cv.Values = cvValues;
            }

            var values = new List<NominationValue>();
            AccessPointFlow apf = new AccessPointFlow();

            foreach (var ap in accespoints)
            {
                var af = ap.AccessPointFlows.FirstOrDefault(a => a.Direction == directionType);

                if (af == null) continue;

                apf = af;

                if (apf.AccessPoint == null) apf.AccessPoint = ap;
                if (apf.AccessPoint.GasStorage.AccessPoints.Count() == 0) apf.AccessPoint.GasStorage.AccessPoints = accespoints;

                break;
            }

            if (apf.AccessPoint == null)
            {
                throw new AccessPointFlowExistException();
            }

            var nomination = new Nomination()
            {
                Channel = Channel.Application,
                GasDay = gasDay,
                Contractor = contractor,
                Name = name,
                Comment = commnet,
                AccessPointFlow = apf,
                CalorificValue = cv,
                Creator = GetCreator(),
                CreateDateTime = DateTime.Now
            };

            for (var index = 0; index < energyValue.Count(); index++)
            {
                values.Add(new NominationValue()
                {
                    HourIndex = index,
                    Energy = new UnitValue(energyValue.ElementAt(index), Unit.Kwh),
                    Volume = new UnitValue(volumeValue.ElementAt(index), Unit.M3),
                    Nomination = nomination
                });
            }

            nomination.Values = values;

            Operation.Add(nomination);

            return RedirectToAction("Index");
        }

        private User GetCreator()
        {
            var orm = OrmFactory.Get(Application.OrmName);
            var sessionCookie = Request.Cookies["sessionId"];

            if (sessionCookie != null)
            {
                OperationFactory.GetSessionOperation(orm, Application.ConnectionString).Refresh(sessionCookie.Value);
                sessionCookie.Expires = DateTime.Now.AddDays(1);
                Response.Cookies.Add(sessionCookie);
            }

            if (sessionCookie != null)
            {
                var user = OperationFactory.GetSessionOperation(orm, Application.OrmName).GetBy(sessionCookie.Value).User;
                return user;
            }

            return OperationFactory.GetUserOperation(orm, Application.ConnectionString).GetAll().First();
        }

        public ActionResult Details(int id)
        {
            var nomination = Operation.Get(id);

            if (nomination == null)
            {
                return HttpNotFound();
            }

            return View(nomination);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Details(FormCollection collection)
        {
            var parentNomination = Operation.Get(Int32.Parse(collection["Id"]));

            if (parentNomination == null)
            {
                return HttpNotFound();
            }

            var agreements = AgreementOperation.GetAll(parentNomination.Contractor, parentNomination.AccessPointFlow.AccessPoint.GasStorage);

            if (!agreements.Any(a => a.Start <= parentNomination.GasDay && a.End >= parentNomination.GasDay))
            {
                throw new AgreementExistException();
            }

            var energyValue = collection.GetValues("value.Energy.Value")

Orms.WebApp/Views/Nominations/Create.cshtml
@model Orms.WebApp.Models.NominationCreateViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Add new Nomination</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.Nomination.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nomination.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nomination.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nomination.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Nomination.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nomination.Comment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nomination.GasDay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nomination.GasDay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nomination.GasDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nomination.AccessPointFlow.AccessPoint.GasStorage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SelectedGasStorageId", Model.GasStorages, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SelectedGasStorageId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contractors, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SelectedContractorId", Model.Contractors, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SelectedContractorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DirectionType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.DirectionType, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DirectionType, "", new { @class = "text-danger" })
            </div>
        </div>

        <table class="table">
            <tr>
                <th>
                    Hour index
                </th>
                <th>
                    Energy Volume
                </th>
                <th>
                    Energy Unit
                </th>
                <th>
                    Volume Value
                </th>
                <th>
                    Volume Unit
                </th>
            </tr>
            @{
                var cvIndex = 0;
            }

            @foreach (var value in @Model.Nomination.Values)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(model => value.HourIndex)
                        @Html.HiddenFor(model => value.HourIndex)
                    </td>
                    <td>
                        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
                        <div class="form-group">
                            @Html.LabelFor(model => value.Energy.Value, "", htmlAttributes: new {@class = "control-label col-md-2"})
                            <div class="col-md-10">
                                @Html.EditorFor(model => value.Energy.Value, new {htmlAttributes = new {@class = "form-control"}})
                                @Html.ValidationMessageFor(model => value.Energy.Value, "", new {@class = "text-danger"})
                            </div>
                        </div>
                    </td>
                    <td>
                        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
                        <div class="form-group">
                            @Html.LabelFor(model => value.Energy.Unit, "", htmlAttributes: new {@class = "control-label col-md-2"})
                            <div class="col-md-10">
                                @Html.DisplayFor(model => value.Energy.Unit, new {htmlAttributes = new {@class = "form-control"}})
                                @Html.ValidationMessageFor(model => value.Energy.Unit, "", new {@class = "text-danger"})
                            </div>
                        </div>
                    </td>
                    <td>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => value.Volume.Value, "", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => value.Volume.Value, new { htmlAttributes = new { @class = "form-control", data_cvindex = cvIndex } })
                                @Html.Hidden("CVval-" + cvIndex, new { htmlAttributes = new { @class = "form-control", @Value = "0", data_cvindex = cvIndex } })
                                @Html.ValidationMessageFor(model => value.Volume.Value, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </td>
                    <td>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => value.Volume.Unit, "", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DisplayFor(model => value.Volume.Unit, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => value.Volume.Unit, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </td>
                </tr>
                {
                    cvIndex++;
                }
            }

        </table>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
                <input type="reset" value="Reset" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>

<script>
    var urlToGet = @Html.Raw(Json.Encode(Url.Action("Get", "Nominations")));

    $( document ).ready(function() {
        getCv($("#Nomination_GasDay").val(), $("#SelectedGasStorageId").val());
    });

    $("#SelectedGasStorageId").change(function () {
        getCv($("#Nomination_GasDay").val(), $("#SelectedGasStorageId").val());
    });

    $("#value_Volume_Value").change(function () {
        var index = this.dataset.cvindex;
        var cv = $("#CVval-" + index);
        var input = $('*[data-cvindex=' + index + ']')[0];
        var value = Number(this.value.replace(",", ".")) / Number(cv.val());

        input.value = value.toString();
    });

    function getCv(gasDay, gasStorageId) {
        var data = {
            gasStorageId: gasStorageId,
            gasDay: gasDay
        };

        var cv;

        $.ajax({
            url: urlToGet,
            type: 'GET',
            data: data,
            success: function (result) {
                cv = result;

                for (var i = 0; i < cv.length; i++) {
                    $("#CVval-" + i).val(cv[i].Value.Value);
                }
            }
        });
    }
</script>

Orms.WebApp/Views/Nominations/Details.cshtml
@model Orms.Models.Nomination

@{
    ViewBag.Title = "Details";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GasDay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.GasDay, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AccessPointFlow.AccessPoint.GasStorage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.AccessPointFlow.AccessPoint.GasStorage.Name, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contractor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Contractor.Name, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Creator.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Creator.Name, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AccessPointFlow.Direction, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.AccessPointFlow.Direction, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FullVersion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.FullVersion, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Channel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Channel, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsAccepted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.IsAccepted, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsLast, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.IsLast, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.CreateDateTime, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <table class="table">
            <tr>
                <th>
                    Hour index
                </th>
                <th>
                    Energy Volume
                </th>
                <th>
                    Energy Unit
                </th>
                <th>
                    Volume Value
                </th>
                <th>
                    Volume Unit
                </th>
            </tr>
            @{
                var cvIndex = 0;
            }

            @foreach (var value in @Model.Values)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(model => value.HourIndex)
                        @Html.HiddenFor(model => value.HourIndex)
                    </td>
                    <td>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => value.Energy.Value, "", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => value.Energy.Value, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => value.Energy.Value, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </td>
                    <td>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => value.Energy.Unit, "", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DisplayFor(model => value.Energy.Unit, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => value.Energy.Unit, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </td>
                    <td>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => value.Volume.Value, "", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => value.Volume.Value, new { htmlAttributes = new { @class = "form-control", data_cvindex = cvIndex } })
                                @Html.Hidden("CVval-" + cvIndex, new { htmlAttributes = new { @class = "form-control", @Value = "0", data_cvindex = cvIndex } })
                                @Html.ValidationMessageFor(model => value.Volume.Value, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </td>
                    <td>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => value.Volume.Unit, "", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DisplayFor(model => value.Volume.Unit, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => value.Volume.Unit, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </td>
                </tr>
                {
                    cvIndex++;
                }
            }

        </table>

        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Recreate" class="btn btn-default" />
                <input type="reset" value="Reset" class="btn btn-default" />
            </div>
        </div>
    </div>
                }

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>

<script>
    var urlToGet = @Html.Raw(Json.Encode(Url.Action("Get", "Nominations")));

    $( document ).ready(function() {
        getCv($("#Nomination_GasDay").val(), $("#SelectedGasStorageId").val());
    });

    $("#SelectedGasStorageId").change(function () {
        getCv($("#Nomination_GasDay").val(), $("#SelectedGasStorageId").val());
    });

    $("#value_Volume_Value").change(function () {
        var index = this.dataset.cvindex;
        var cv = $("#CVval-" + index);
        var input = $('*[data-cvindex=' + index + ']')[0];
        var value = Number(this.value.replace(",", ".")) / Number(cv.val());

        input.value = value.toString();
    });

    function getCv(gasDay, gasStorageId) {
        var data = {
            gasStorageId: gasStorageId,
            gasDay: gasDay
        };

        var cv;

        $.ajax({
            url: urlToGet,
            type: 'GET',
            data: data,
            success: function (result) {
                cv = result;

                for (var i = 0; i < cv.length; i++) {
                    $("#CVval-" + i).val(cv[i].Value.Value);
                }
            }
        });
    }
</script>

Orms.WebApp/Views/Nominations/Index.cshtml
@using Orms.Models
@model Orms.WebApp.Models.NominationListViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Nomination lists</h2>

<p>
    @Html.ActionLink("Create new Nomination", "Create")
</p>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new {@class = "text-danger"})
    <div class="form-group">
        @Html.Label("GasDay", "", htmlAttributes: new {@class = "control-label col-md-2"})
        <div class="col-md-10">
            @Html.Editor("gasDay", new {htmlAttributes = new {@class = "form-control", @Value = Model.GasDay.ToString() }})
            @Html.ValidationMessage("gasDay", "", new {@class = "text-danger"})
        </div>
    </div>

    <div class="form-group">
        <input type="submit" value="Change" class="btn btn-default" />
        <input type="reset" value="Reset" class="btn btn-default" />
    </div>
}

<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>
            GasStorage
        </th>
        <th>
            GasDay
        </th>
        <th>
            Contractor
        </th>
        <th>
            User
        </th>
        <th>
            Channel
        </th>
        <th>
            CreateDateTime
        </th>
        <th>
            Version
        </th>
        <th>
            IsLastOrder
        </th>
        <th>
            IsAccepted
        </th>
        <th>
            Direction
        </th>
        <th></th>
        <th></th>
    </tr>

    @foreach (var item in Model.Nominations)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AccessPointFlow.AccessPoint.GasStorage.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GasDay)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Contractor.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Creator.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Channel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreateDateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FullVersion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsLast)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsAccepted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AccessPointFlow.Direction)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.Id })
            </td>
            <td>
                @if (!item.IsAccepted)
                {
                    @Html.ActionLink("Accepted", "Accepted", new {id = item.Id})
                }
            </td>
        </tr>
    }

</table>