Orms.WebApp/Controllers/ContractorsController.cs
using System.Web.Mvc;
using Orms.DataAccessFactory;
using Orms.DataAccessFactory.OperationFactories;
using Orms.DataAccessHelper.Operations.Interfaces;
using Orms.Models;
using Orms.WebApp.Models;

namespace Orms.WebApp.Controllers
{
    public class ContractorsController : Controller
    {
        private readonly IContractorOperation _operation;

        public ContractorsController()
        {
            var orm = OrmFactory.Get(Application.OrmName);
            _operation = OperationFactory.GetContractorOperation(orm, Application.ConnectionString);
        }

        public ActionResult Index()
        {
            var contractors = _operation.GetAll();

            return View(contractors);
        }

        public ActionResult Details(int id)
        {
            var contractor = _operation.Get(id);

            if (contractor == null)
            {
                return HttpNotFound();
            }

            var orm = OrmFactory.Get(Application.OrmName);

            var model = new ContractorDetailsViewModel()
            {
                Contractor = contractor,
                Contacts = _operation.GetAll(contractor),
                Agreements = OperationFactory.GetAgreementOperation(orm, Application.ConnectionString).GetAll(contractor),
                Users = OperationFactory.GetUserOperation(orm, Application.ConnectionString).Get(contractor),
                ContractorId = contractor.Id
            };

            return View(model);
        }

        [ValidateAntiForgeryToken]
        public ActionResult CreateContact(ContractorDetailsViewModel model)
        {
            if (ModelState.IsValid)
            {
                var contractor = _operation.Get(model.ContractorId);

                if (contractor == null)
                {
                    return HttpNotFound();
                }

                model.NewContact.Contractor = contractor;
                _operation.Add(model.NewContact, model.ContractorId);
            }

            return RedirectToAction("Details", new { id = model.ContractorId });
        }

        public ActionResult Create()
        {
           return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name, Code, Adress")] Contractor contractor)
        {
            if (ModelState.IsValid)
            {
                _operation.Add(contractor);
                return RedirectToAction("Index");
            }

            return View(contractor);
        }
    }
}

Orms.WebApp/Views/Contractors/Create.cshtml
@model Orms.Models.Contractor

@{
    ViewBag.Title = "Create";
}

<h2>Add new contractor</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Adress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Adress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
                <input type="reset" value="Reset" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Orms.WebApp/Views/Contractors/Details.cshtml
@using Orms.Models.Extensions
@model Orms.WebApp.Models.ContractorDetailsViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Contractor @Model.Contractor.Name</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contractor.Name)
        </dd>

        <dt>
            Code
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contractor.Code)
        </dd>


        <dt>
            Adress
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contractor.Adress)
        </dd>
    </dl>

    <h4>Add new contact</h4>
    @using (Html.BeginForm("CreateContact", "Contractors", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(model => model.NewContact.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NewContact.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NewContact.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NewContact.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NewContact.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NewContact.FirstName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NewContact.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NewContact.LastName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NewContact.LastName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NewContact.Adress, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NewContact.Adress, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NewContact.Adress, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NewContact.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NewContact.Phone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NewContact.Phone, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NewContact.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NewContact.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NewContact.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            @Html.HiddenFor(model => model.ContractorId, new { htmlAttributes = new { @class = "form-control", @Value = @Model.Contractor.Id } })

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                    <input type="reset" value="Reset" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <h4>Contact lists</h4>
    <table class="table">
        <tr>
            <th>
                Name
            </th>
            <th>
                First name
            </th>
            <th>
                Last name
            </th>
            <th>
                Adress
            </th>
            <th>
                Email
            </th>
            <th>
                Phone
            </th>
        </tr>

        @foreach (var item in Model.Contacts) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Adress)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Phone)
                </td>
            </tr>
        }
    </table>

<h4>Agreement lists</h4>
    <table class="table">
        <tr>
            <th>
                Gas storage
            </th>
            <th>
                Start
            </th>
            <th>
                End
            </th>
            <th>
                Status
            </th>
        </tr>

        @foreach (var item in Model.Agreements)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.GasStorage.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Start)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.End)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
            </tr>
        }
    </table>

<h4>User lists</h4>
    <table class="table">
        <tr>
            <th>
                Name
            </th>
            <th>
                Email
            </th>
            <th>
                Last activity date
            </th>
        </tr>

        @foreach (var item in Model.Users)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastActivityDateTime)
                </td>
            </tr>
        }
    </table>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

Orms.WebApp/Views/Contractors/Index.cshtml
@using Orms.Domains.Enums
@using Orms.Models.Extensions
@model IEnumerable<Orms.Models.Contractor>

@{
    ViewBag.Title = "Index";
}

<h2>Contractor lists</h2>

<p>
    @Html.ActionLink("Create new Contractor", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>
            Code
        </th>
        <th>
            Adress
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Adress)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id=item.Id })
            </td>
        </tr>
    }

</table>